Ensure it runs twice if it fails

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,16 +40,33 @@ jobs:
         kicad-cli pcb export glb --subst-models --include-tracks \
           --include-inner-copper --include-silkscreen --include-soldermask --fuse-shapes \
           --cut-vias-in-body --fill-all-vias --drill-origin --min-distance=0.100mm -f \
-          -o "$outputDir/sidekick.glb" "$projectDir/sidekick.kicad_pcb"  || ( [ -f sidekick.glb ] && echo "sidekick.glb found, continuing..." || exit )
+          -o "$outputDir/sidekick.glb" "$projectDir/sidekick.kicad_pcb" || true
 
+        if [ -f "$outputDir/sidekick.glb" ]; then
+          echo "sidekick.glb found, continuing..."
+        else
+          echo "Error: sidekick.glb not created."
+          kicad-cli pcb export glb --subst-models --include-tracks \
+          --include-inner-copper --include-silkscreen --include-soldermask --fuse-shapes \
+          --cut-vias-in-body --fill-all-vias --drill-origin --min-distance=0.100mm -f \
+          -o "$outputDir/sidekick.glb" "$projectDir/sidekick.kicad_pcb" || true
+        fi
 
         # Export sidekick-pcb.glb (without components)
         kicad-cli pcb export glb --subst-models --no-components --include-tracks \
           --include-inner-copper --include-silkscreen --include-soldermask --fuse-shapes \
           --cut-vias-in-body --fill-all-vias --drill-origin --min-distance=0.100mm -f \
-          -o "$outputDir/sidekick-pcb.glb" "$projectDir/sidekick.kicad_pcb"   || ( [ -f sidekick-pcb.glb ] && echo "sidekick-pcb.glb found, continuing..." || exit )
+          -o "$outputDir/sidekick-pcb.glb" "$projectDir/sidekick.kicad_pcb" || true
 
-
+        if [ -f "$outputDir/sidekick-pcb.glb" ]; then
+          echo "sidekick-pcb.glb found, continuing..."
+        else
+          echo "Error: sidekick-pcb.glb not created."
+          kicad-cli pcb export glb --subst-models --no-components --include-tracks \
+          --include-inner-copper --include-silkscreen --include-soldermask --fuse-shapes \
+          --cut-vias-in-body --fill-all-vias --drill-origin --min-distance=0.100mm -f \
+          -o "$outputDir/sidekick-pcb.glb" "$projectDir/sidekick.kicad_pcb" || true
+        fi
 
         echo "Packing glb files"
         # Optimize sidekick.glb with gltfpack
